apiVersion: argoproj.io/v1alpha1
kind: Application        # <--- This one HAS a 'spec' field
metadata:
  name: mando-stack
  namespace: argocd
spec:                   # <--- 'spec' belongs here
  project: default
  source:
    repoURL: 'https://github.com/Chandra179/mando'
    path: '.'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    # Optional settings
    # automated:
    #   prune: true
    #   selfHeal: true